version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: ./start.sh
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_TOKEN=${SECRET_TOKEN}    
      - DB_URI=${DB_URI}
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/gpc/gcp_credentials.json
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./gcp-credentials.json: /etc/gpc/gcp-credentials.json
  frontend:
    build:
      context: ./frontend/app
    environment:
      - SECRET_BACKEND_URL=${BACKEND_URL}
      - SECRET_TOKEN=${SECRET_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    container_name: gamedb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5