name: Deploy

on:
  push:
    branches: [ release ]

jobs: 
  deploy_to_cloud_run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker
      run: |-
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

    - name: Tag and push frontend image to Artifact Registry
      env:
        ARTIFACT_REPOSITORY: ${{ secrets.FRONTEND_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |  
        docker build -t $ARTIFACT_REPOSITORY/frontend:$IMAGE_TAG -t $ARTIFACT_REPOSITORY/frontend:latest ./frontend/app
        docker push -a $ARTIFACT_REPOSITORY/frontend

    - name: Tag and push backend image to Artifact Registry
      env:
        ARTIFACT_REPOSITORY: ${{ secrets.BACKEND_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |  
        docker build -t $ARTIFACT_REPOSITORY/backend:$IMAGE_TAG -t $ARTIFACT_REPOSITORY/backend:latest ./backend
        docker push -a $ARTIFACT_REPOSITORY/backend

    - name: Deploy to Cloud Run
      run: |
          gcloud run deploy nationle-frontend \
            --image ${{ secrets.FRONTEND_REPOSITORY }}/frontend:${{ github.sha }} \
            --region europe-west3 \
            --platform managed \
            --allow-unauthenticated
        
          gcloud run deploy nationle-backend \
            --image ${{ secrets.BACKEND_REPOSITORY }}/backend:${{ github.sha }} \
            --region europe-west3 \
            --platform managed \
            --allow-unauthenticated 
